var num1=+prompt("Enter The first subject")
var num2=+prompt("Enter The first subject")
var num3=+prompt("Enter The first subject")
var num4=+prompt("Enter The first subject")
var num5=+prompt("Enter The first subject")
var num6=+prompt("Enter The first subject")
var sum=num1+num2+num3+num4+num5+num6 ;
document.write("the sum="+sum)
var avg=sum/6;
document.write(" the average="+avg)
var percentage=(sum/100)*100;
document.write(" the percentage="+percentage)